### PR TITLE
Replaced boxart for a Yu-Gi-Oh game

### PR DESCRIPTION
**Pull request by Hawaka743**
Replaced boxart for "Yu-Gi-Oh! - Sugoroku no Sugoroku (Japan)". I meant to upload this with the other Yu-Gi-Oh boxarts, but somehow it got lost (I accidentally downloaded the original image into a different folder on my pc.)

### CODE REVIEW

**Comment by RobLoach** [comment]
The image quality of this looks pretty bad. Is there another one out there?

**Comment by Hawaka743** [comment]
Since you asked I looked one more time, and found this:
yu-gi-oh - sugoroku no sugoroku japan
It might be somewhat better.

**Comment by Hawaka743** [comment]
Just for reference here is the previous image:
yu-gi-oh - sugoroku no sugoroku japan
And here is the new one.
yu-gi-oh - sugoroku no sugoroku japan

**Comment by RobLoach** [comment]
Sounds good! Thanks a lot for the updates.

**Pull request merged**
