### PR TITLE
Replaced some boxart

### PR DESCRIPTION
**Pull request by Hawaka743**
Replaced some boxart with better quality ones.

### CODE REVIEW

**Comment by Hawaka743** [comment]
The images could be made smaller by using posterization. Unfortunately it would shrink them by only about 50-100 kb's without any noticeable quality loss. (posterization limits the amount of colours in an image)

**Comment by MarcoEstevez** [comment]
I don't like the idea to make images fit in 512x512, since all portrait systems will get affected lossing resolution.

I mean for example, super - famicon games looks fantastic on RA-XMB and fit well, but the west releases used to be landscape, and thus due to the 512 wide rule, has less resolution. 

image

image

**Comment by Hawaka743** [comment]
That's a good point. I haven't considered that.

**Comment by MarcoEstevez** [comment]
Nop, Great job @Hawaka743 as always  :-D

LGTM

**Pull request merged**
