### PR TITLE
Overhauled all GBA boxarts

### PR DESCRIPTION
**Pull request by Jaffacakelover**
REPLACED ALL BOXART IMAGE FILES: Separate from 2021 commits (started from earlier repository).
* Sourced and added new cover images:
** Europe covers (France, Germany, Netherlands etc.): Were previously copies of USA covers renamed.
** Japan covers.
** China iQue covers (created missing / unreleased covers).
** Game Boy Advance Video covers.
** Others, such as Game Boy Camera and Play-Yan.
* Added all covers missing from rdb database.
* Replaced all covers with higher resolution images (up to 500px width from 256px).
* Resized all artwork to correct ratios:
** USA / Europe = 1:1 (125x125mm, 500x500px)
** Japan / Korea = (135x87mm, 500x315px)
** China iQue = (est. 130x115mm, 500x450px)
** Game Boy Advance Video = (est. 100x140mm, 360x500px)
* Cleanup on many images to fix colours / remove scratches & wear.
* 'Rating pending' labels on covers replaced with release ratings.
* Created / sourced images for hacks / prototypes.
* Compressed all PNGs using pingo / pinga.

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
Great work correcting wrong regions and adding missing boxes, but why have you resized all existing ones from 512 wide to 500?

**Comment by MarcoEstevez** [comment]
Here is another example, the replacement image looks blurry, lacking definition and in general, to be honest inferior to the existing one

image

**Comment by Jaffacakelover** [comment]
Many of the source photos on the internet were 500px, so I guessed that the database ones had been scaled up from that size. Sized everything down again for consistancy and maintain quality / improve quality a tiny bit.

I may have been working from an outdated database (2020) which is missing over the latest 2021 changes, such as an improvement to the image above (especially as this took months of work). I could comb back through comparing this pull request to the August/Sep 2021 repo for which pics are better?

**Comment by RobLoach** [comment]
I've brought in the additions from this PR through a different pull request. This will need a conflict fix, and another review. Thanks all!

**Comment by masanasake** [comment]
@Jaffacakelover would you mind closing this PR since it was edited and merged? Thanks

**Pull request closed without merging**
